name: Continuous Integration

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  shared:
    name: Nomad
    uses: betsecure/nomad-workflows/.github/workflows/go.ci.yml@main
    secrets: inherit
