# This workflow automatically merges Dependabot PRs for trusted dependencies.

on:
  workflow_call:
    secrets:
      DEPENDABOT_GITHUB_TOKEN:
        required: true

jobs:
  dependabot:
    name: Dependabot
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Load Dependabot meta-data
        uses: dependabot/fetch-metadata@v1.3.4
        id: dependabot-metadata

      - name: Auto-merge minor/patch updates to approved dependencies
        run: gh pr comment "${{ github.event.pull_request.html_url }}" --body "@dependabot merge"
        env:
          GH_TOKEN: ${{ secrets.DEPENDABOT_GITHUB_TOKEN }}
        if: >
          steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' && (
            (steps.dependabot-metadata.outputs.package-ecosystem == 'go_modules' && (
              startsWith(steps.dependabot-metadata.outputs.dependency-names, 'github.com/betsecure/') ||
              startsWith(steps.dependabot-metadata.outputs.dependency-names, 'github.com/dogmatiq/') ||
              startsWith(steps.dependabot-metadata.outputs.dependency-names, 'golang.org/x/') ||
              steps.dependabot-metadata.outputs.dependency-names == 'github.com/google/go-cmp' ||
              steps.dependabot-metadata.outputs.dependency-names == 'github.com/jackc/pgx/v4' ||
              steps.dependabot-metadata.outputs.dependency-names == 'google.golang.org/grpc' ||
              steps.dependabot-metadata.outputs.dependency-names == 'google.golang.org/protobuf' ||
              steps.dependabot-metadata.outputs.dependency-names == 'go.uber.org/zap'
            ))
            ||
            (steps.dependabot-metadata.outputs.package-ecosystem == 'npm_and_yarn' && (
              startsWith(steps.dependabot-metadata.outputs.dependency-names, '@playwright/') ||
              startsWith(steps.dependabot-metadata.outputs.dependency-names, '@testing-library/') ||
              startsWith(steps.dependabot-metadata.outputs.dependency-names, '@types/') ||
              startsWith(steps.dependabot-metadata.outputs.dependency-names, '@typescript-eslint/') ||
              startsWith(steps.dependabot-metadata.outputs.dependency-names, 'eslint') ||
              startsWith(steps.dependabot-metadata.outputs.dependency-names, 'jest') ||
              startsWith(steps.dependabot-metadata.outputs.dependency-names, 'prettier') ||
              steps.dependabot-metadata.outputs.dependency-names == 'msw' ||
              steps.dependabot-metadata.outputs.dependency-names == 'typescript'
            ))
          )
