on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Release

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish GitHub release
        uses: eloquent/github-release-action@v3.1.1
