# This workflow publishes a GitHub release based on a Git tag.

name: Publish Release

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish release

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish release
        uses: eloquent/github-release-action@v2
