name: Continuous Integration

on:
  workflow_call:
    secrets:
      READ_ALL_SSH_KEY:
        required: false

env:
  GOPRIVATE: github.com/betsecure/*
  READ_ALL_SSH_KEY: ${{ secrets.READ_ALL_SSH_KEY }} # See https://stackoverflow.com/a/70249520.

jobs:
  go:
    name: Go
    runs-on: ubuntu-latest

    services:
      postgres:
        image: kartoza/postgis:14-3
        options: >-
          --health-cmd pg_isready
          --health-interval 2s
          --health-timeout 10s
          --health-retries 10
        ports:
          - 5432/tcp
        env:
          POSTGRES_USER: nomad
          POSTGRES_PASS: nomad

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1
          check-latest: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git to use SSH
        if: env.READ_ALL_SSH_KEY != ''
        run: git config --global url.ssh://git@github.com/betsecure/.insteadOf https://github.com/betsecure/

      - name: Setup SSH key for access to dependencies
        if: env.READ_ALL_SSH_KEY != ''
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.READ_ALL_SSH_KEY }}

      - name: Make
        run: make ci
        env:
          NOMAD_TEST_POSTGRES_PORT: ${{ job.services.postgres.ports['5432'] }}
