on:
  workflow_call:
    secrets:
      READ_ALL_SSH_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      AWS_ROLE:
        required: true

env:
  GOPRIVATE: github.com/betsecure/*
  READ_ALL_SSH_KEY: ${{ secrets.READ_ALL_SSH_KEY }} # See https://stackoverflow.com/a/70249520.

jobs:
  docker:
    name: Go + Docker
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1
          check-latest: true

      - name: Enable Go module and build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git to use SSH
        if: env.READ_ALL_SSH_KEY != ''
        run: git config --global url.ssh://git@github.com/betsecure/.insteadOf https://github.com/betsecure/

      - name: Setup SSH key for access to dependencies
        if: env.READ_ALL_SSH_KEY != ''
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.READ_ALL_SSH_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-skip-session-tagging: true
          role-duration-seconds: 900

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        env:
          DOCKER_REPO: ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}
          DOCKER_TAGS: ${{ github.ref_name }}
        run: docker buildx create --use && make docker-push
