# This workflow publishes a GitHub release and updates the Nomad tap.
# It replaces "generic.release.yml"; do not use them together.

name: Publish Homebrew Release

on:
  workflow_call:
    secrets:
      READ_ALL_SSH_KEY:
        required: false
      HOMEBREW_GITHUB_TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

env:
  GOPRIVATE: github.com/betsecure/*
  READ_ALL_SSH_KEY: ${{ secrets.READ_ALL_SSH_KEY }} # See https://stackoverflow.com/a/70249520.

jobs:
  release:
    name: Publish Homebrew release
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1
          check-latest: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git to use SSH
        if: env.READ_ALL_SSH_KEY != ''
        run: git config --global url.ssh://git@github.com/betsecure/.insteadOf https://github.com/betsecure/

      - name: Setup SSH key for access to dependencies
        if: env.READ_ALL_SSH_KEY != ''
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.READ_ALL_SSH_KEY }}

      - name: Build archives containing release binaries
        run: make archives

      - name: Publish GitHub release
        uses: eloquent/github-release-action@assets-input
        with:
          assetsYAML: |
            - path: artifacts/archives/*

      - name: Build Homebrew formula
        run: make homebrew

      - name: Upload Homebrew formula
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
        with:
          source-directory: artifacts/homebrew
          destination-github-username: "betsecure"
          destination-repository-name: "homebrew-nomad"

      - name: Publish Slack notification
        uses: ravsamhq/notify-slack-action@v1
        if: always()
        with:
          status: ${{ job.status }}
          notify_when: "failure,warnings"
          notification_title: "<{run_url}|*{workflow}* {status_message}> for <{repo_url}|{repo}>"
          message_format: "Caused by ${{ env.CAUSE_MESSAGE }}(<{commit_url}|{branch}@{commit_sha}>)"
          footer: ""
        env:
          CAUSE_MESSAGE: ${{ github.event.head_commit.message && '"${{ github.event.head_commit.message }}" ' || '' }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
