# This workflow publishes a GitHub release based on a Git tag, and attaches
# assets that are archives containing the release binaries.

name: Publish Release

on:
  workflow_call:
    secrets:
      READ_ALL_SSH_KEY:
        required: false
      SLACK_WEBHOOK_URL:
        required: true

env:
  GOPRIVATE: github.com/betsecure/*
  READ_ALL_SSH_KEY: ${{ secrets.READ_ALL_SSH_KEY }} # See https://stackoverflow.com/a/70249520.

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1
          check-latest: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git to use SSH
        if: env.READ_ALL_SSH_KEY != ''
        run: git config --global url.ssh://git@github.com/betsecure/.insteadOf https://github.com/betsecure/

      - name: Setup SSH key for access to dependencies
        if: env.READ_ALL_SSH_KEY != ''
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.READ_ALL_SSH_KEY }}

      - name: Build archives containing release binaries
        run: make archives

      - name: Publish release
        uses: eloquent/github-release-action@v2
        with:
          assets:
            - path: artifacts/archives/*

      - name: Publish Slack notification
        uses: ravsamhq/notify-slack-action@v1
        if: always()
        with:
          status: ${{ job.status }}
          notify_when: "failure,warnings"
          notification_title: "<{run_url}|*{workflow}* {status_message}> for <{repo_url}|{repo}>"
          message_format: 'Caused by "${{ github.event.head_commit.message }}" (<{commit_url}|{branch}@{commit_sha}>)'
          footer: ""
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
